#!/usr/bin/env perl

use v5.14;

my $msg = shift;
my @issues = ($msg =~ /\#(\d+)/g);
exit(1) if (!@issues );
my $repo_uri = `git config --get remote.origin.url`;
my ($user,$repo) = ($repo_uri =~ /(\w+)\/([^.]+)/);
for my $i (@issues) {
  my $issue = `wget -O - https://github.com/$user/$repo/issues/$i`;
  die "Issue $issue no existe" if !$issue;
}
